site_name: Expressive
site_description: A Data Mapper layer on top of Eloquent
site_url: https://wendelladriel.github.io/expressive
repo_url: https://github.com/wendelladriel/expressive
repo_name: wendelladriel/expressive

theme:
  # Customize Material for MkDocs: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Testing: testing.md
